config/routes.rb
Rails.application.routes.draw do
  resources :telefones
  resources :pessoas
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pessoa.rb
class Pessoa < ApplicationRecord

end

app/models/telefone.rb
class Telefone < ApplicationRecord
    belongs_to :pessoa
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pessoas_controller.rb
class PessoasController < ApplicationController
  before_action :set_pessoa, only: [:show, :edit, :update, :destroy]

  # GET /pessoas
  # GET /pessoas.json
  def index
    @pessoas = Pessoa.all
  end

  # GET /pessoas/1
  # GET /pessoas/1.json
  def show
  end

  # GET /pessoas/new
  def new
    @pessoa = Pessoa.new
  end

  # GET /pessoas/1/edit
  def edit
  end

  # POST /pessoas
  # POST /pessoas.json
  def create
    @pessoa = Pessoa.new(pessoa_params)

    respond_to do |format|
      if @pessoa.save
        format.html { redirect_to @pessoa, notice: 'Pessoa was successfully created.' }
        format.json { render :show, status: :created, location: @pessoa }
      else
        format.html { render :new }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pessoas/1
  # PATCH/PUT /pessoas/1.json
  def update
    respond_to do |format|
      if @pessoa.update(pessoa_params)
        format.html { redirect_to @pessoa, notice: 'Pessoa was successfully updated.' }
        format.json { render :show, status: :ok, location: @pessoa }
      else
        format.html { render :edit }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pessoas/1
  # DELETE /pessoas/1.json
  def destroy
    @pessoa.destroy
    respond_to do |format|
      format.html { redirect_to pessoas_url, notice: 'Pessoa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pessoa
      @pessoa = Pessoa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pessoa_params
      params.require(:pessoa).permit(:nome, :sobrenome, :documento, :email, :data_nascimento)
    end
end

app/controllers/telefones_controller.rb
class TelefonesController < ApplicationController
  before_action :set_telefone, only: [:show, :edit, :update, :destroy]

  # GET /telefones
  # GET /telefones.json
  def index
    @telefones = Telefone.all
  end

  # GET /telefones/1
  # GET /telefones/1.json
  def show
  end

  # GET /telefones/new
  def new
    @telefone = Telefone.new
  end

  # GET /telefones/1/edit
  def edit
  end

  # POST /telefones
  # POST /telefones.json
  def create
    @telefone = Telefone.new(telefone_params)

    respond_to do |format|
      if @telefone.save
        format.html { redirect_to @telefone, notice: 'Telefone was successfully created.' }
        format.json { render :show, status: :created, location: @telefone }
      else
        format.html { render :new }
        format.json { render json: @telefone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /telefones/1
  # PATCH/PUT /telefones/1.json
  def update
    respond_to do |format|
      if @telefone.update(telefone_params)
        format.html { redirect_to @telefone, notice: 'Telefone was successfully updated.' }
        format.json { render :show, status: :ok, location: @telefone }
      else
        format.html { render :edit }
        format.json { render json: @telefone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /telefones/1
  # DELETE /telefones/1.json
  def destroy
    @telefone.destroy
    respond_to do |format|
      format.html { redirect_to telefones_url, notice: 'Telefone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_telefone
      @telefone = Telefone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def telefone_params
      params.require(:telefone).permit(:numero, :ddd, :tipo, :preferencial)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pessoas_helper.rb
module PessoasHelper
end

app/helpers/telefones_helper.rb
module TelefonesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Renter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pessoas/_form.html.erb
<%= form_with(model: pessoa, local: true) do |form| %>
  <% if pessoa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pessoa.errors.count, "error") %> prohibited this pessoa from being saved:</h2>

      <ul>
        <% pessoa.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :sobrenome %>
    <%= form.text_field :sobrenome %>
  </div>

  <div class="field">
    <%= form.label :documento %>
    <%= form.text_field :documento %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :data_nascimento %>
    <%= form.date_select :data_nascimento %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pessoas/edit.html.erb
<h1>Editing Pessoa</h1>

<%= render 'form', pessoa: @pessoa %>

<%= link_to 'Show', @pessoa %> |
<%= link_to 'Back', pessoas_path %>

app/views/pessoas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pessoas</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Sobrenome</th>
      <th>Documento</th>
      <th>Email</th>
      <th>Data nascimento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pessoas.each do |pessoa| %>
      <tr>
        <td><%= pessoa.nome %></td>
        <td><%= pessoa.sobrenome %></td>
        <td><%= pessoa.documento %></td>
        <td><%= pessoa.email %></td>
        <td><%= pessoa.data_nascimento %></td>
        <td><%= link_to 'Show', pessoa %></td>
        <td><%= link_to 'Edit', edit_pessoa_path(pessoa) %></td>
        <td><%= link_to 'Destroy', pessoa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pessoa', new_pessoa_path %>

app/views/pessoas/new.html.erb
<h1>New Pessoa</h1>

<%= render 'form', pessoa: @pessoa %>

<%= link_to 'Back', pessoas_path %>

app/views/pessoas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @pessoa.nome %>
</p>

<p>
  <strong>Sobrenome:</strong>
  <%= @pessoa.sobrenome %>
</p>

<p>
  <strong>Documento:</strong>
  <%= @pessoa.documento %>
</p>

<p>
  <strong>Email:</strong>
  <%= @pessoa.email %>
</p>

<p>
  <strong>Data nascimento:</strong>
  <%= @pessoa.data_nascimento %>
</p>

<%= link_to 'Edit', edit_pessoa_path(@pessoa) %> |
<%= link_to 'Back', pessoas_path %>

app/views/telefones/_form.html.erb
<%= form_with(model: telefone, local: true) do |form| %>
  <% if telefone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(telefone.errors.count, "error") %> prohibited this telefone from being saved:</h2>

      <ul>
        <% telefone.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :numero %>
    <%= form.text_field :numero %>
  </div>

  <div class="field">
    <%= form.label :ddd %>
    <%= form.number_field :ddd %>
  </div>

  <div class="field">
    <%= form.label :tipo %>
    <%= form.number_field :tipo %>
  </div>

  <div class="field">
    <%= form.label :preferencial %>
    <%= form.check_box :preferencial %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/telefones/edit.html.erb
<h1>Editing Telefone</h1>

<%= render 'form', telefone: @telefone %>

<%= link_to 'Show', @telefone %> |
<%= link_to 'Back', telefones_path %>

app/views/telefones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Telefones</h1>

<table>
  <thead>
    <tr>
      <th>Numero</th>
      <th>Ddd</th>
      <th>Tipo</th>
      <th>Preferencial</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @telefones.each do |telefone| %>
      <tr>
        <td><%= telefone.numero %></td>
        <td><%= telefone.ddd %></td>
        <td><%= telefone.tipo %></td>
        <td><%= telefone.preferencial %></td>
        <td><%= link_to 'Show', telefone %></td>
        <td><%= link_to 'Edit', edit_telefone_path(telefone) %></td>
        <td><%= link_to 'Destroy', telefone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Telefone', new_telefone_path %>

app/views/telefones/new.html.erb
<h1>New Telefone</h1>

<%= render 'form', telefone: @telefone %>

<%= link_to 'Back', telefones_path %>

app/views/telefones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Numero:</strong>
  <%= @telefone.numero %>
</p>

<p>
  <strong>Ddd:</strong>
  <%= @telefone.ddd %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @telefone.tipo %>
</p>

<p>
  <strong>Preferencial:</strong>
  <%= @telefone.preferencial %>
</p>

<%= link_to 'Edit', edit_telefone_path(@telefone) %> |
<%= link_to 'Back', telefones_path %>